### PR TITLE
Invalidate cache when role is removed from default group

### PR DESCRIPTION
**Pull request by wcmitchell**
Signed-off-by: Chris Mitchell <cmitchel@redhat.com>

## Link(s) to Jira
https://projects.engineering.redhat.com/browse/RHCLOUD-8126

## Description of Intent of Change(s)
Cache wasn't be invalidated when roles were removed from the default group. This change should resolve that.

## Local Testing
Use the reproducer script linked in the above Jira to test. Will need to change the target server and UUID for default group to your local configuration before testing.

## Checklist
- [ ] if API spec changes are required, is the spec updated?

- [ ] are there any pre/post merge actions required? if so, document here.

- [ ] are theses changes covered by unit tests?

- [ ] if warranted, are documentation changes accounted for?

- [ ] does this require migration changes?
  - [ ] if yes, are they backwards compatible?

- [ ] is there known, direct impact to dependent teams/components?
  -  if yes, how will this be handled?

### CODE REVIEW

**Comment by astrozzc** [comment]
Tested locally, works well. I assume this would be ensured by feature tests

**Comment by astrozzc** [comment]
Hmm, I am wondering how tests change the access for the platform_default group since we don't allow modifying the system and platform_default role. Hopefully we don't have another bug somewhere @catastrophe-brandon

**Comment by coderbydesign** [comment]
@astrozzc you can still add/remove roles to and from the default group, you just can't modify the permissions on those system roles. Is that what you're referring to?

**Comment by wcmitchell** [comment]
I'm not sure about unit testing unless we assume that the test suites will have cache access, if so then there may be a way to fold @catastrophe-brandon's testing script into a test method. I can do some digging. Not sure on the unit tests, though, will roll back through and check.

**Comment by astrozzc** [comment]
> @astrozzc you can still add/remove roles to and from the default group, you just can't modify the permissions on those system roles. Is that what you're referring to?

Ah, you are right! Now I remember. I was confused by this: https://github.com/RedHatInsights/insights-rbac/blob/master/rbac/management/group/view.py#L315, which is only modifying the group, not add/remove roles.

**Pull request merged**
