### PR TITLE
Move OneOf Access defintion to separate component

### PR DESCRIPTION
**Pull request by semtexzv**
The inline specification of OneOf model does not play nice with client generator for golang, 
and is blocking [patchman-engine](https://github.com/RedHatInsights/patchman-engine) integration.

Semantics before and after the change are the same.

### CODE REVIEW

**Comment by coderbydesign** [comment]
@semtexzv we will likely end up closing this in favor of #214 given there are issues with the OpenAPI generator project with regard to `oneOf` that are affecting other clients as well. This unfortunately doesn't seem to resolve the issue with other languages.

**Comment by coderbydesign** [comment]
@semtexzv if you're able to, please confirm the latest spec changes on `master` in CI have resolved this issue for you? If so, we can close this out. Thanks!

**Comment by coderbydesign** [comment]
Closing, but please let me know if you have any concerns @semtexzv.

**Comment by semtexzv** [comment]
@coderbydesign The changes seem to work fine for our generated client. Thanks.

**Pull request closed without merging**
