### PR TITLE
Change to grant workflows read permission to approver role

### PR DESCRIPTION
**Pull request by hsong-rh**
Changed permissions for approver roles.

### CODE REVIEW

**Comment by hsong-rh** [comment]
@chambridge CI build failed, but I feel it's unrelated with my change. Could you take a look?

**Comment by hsong-rh** [comment]
@chambridge One question, will this PR will deploy to QA environment? I just checked `qa.cloud.paas.psi.redhat.com`, `Approval Approver` still has old permissions. Thanks,

**Comment by chambridge** [comment]
This will be deployed today.

**Comment by chambridge** [comment]
You can follow slack channel #insights-rbac for details.

**Pull request merged**
