### PR TITLE
Sync with master

### PR DESCRIPTION
**Pull request by astrozzc**
We have changed QA to sync with stable branch, which is behind now. We have to sync with master to catch up with latest changes.

### CODE REVIEW

**Comment by coderbydesign** [comment]
cc: @chambridge

**Comment by coderbydesign** [comment]
This makes sense to me. Not sure what the `jenkins/pr-merge` failure is about though? @astrozzc

**Comment by astrozzc** [comment]
> This makes sense to me. Not sure what the `jenkins/pr-merge` failure is about though? @astrozzc

Yes, this is caused by https://github.com/RedHatInsights/insights-rbac/blob/master/Jenkinsfile-smoke.groovy#L8

We have to change it to execSmokeTest: https://github.com/RedHatInsights/insights-pipeline-lib/blob/master/convert-to-v3.py#L37

**Comment by astrozzc** [comment]
Now that smoke test env creation is fixed
https://github.com/RedHatInsights/e2e-deploy/pull/858
https://github.com/RedHatInsights/e2e-deploy/pull/861

And the tests are passing, this pr is ready to be merged.

**Pull request merged**
