### PR TITLE
[RHCLOUD-27277] Change type of value in ResourceDefinitionFilter component of openapi spec

### PR DESCRIPTION
**Pull request by lpichler**
Change is from type `string` to one of:
`string`
`null`
**array**: elements are one of:
`string`
`null`

### Links
https://issues.redhat.com/browse/RHCLOUD-27277

### CODE REVIEW

**Review by romanblanco — APPROVED** [review]

**Comment by vkrizan** [comment]
@lpichler can you please also change your documentation? Thank you!

**Comment by romanblanco** [comment]
@vkrizan, you mean at https://developers.redhat.com/api-catalog/?

**Comment by vkrizan** [comment]
I've meant this one: https://github.com/RedHatInsights/insights-rbac/blob/master/docs/source/management/role.rst#resource-definitions
Libor might know more...

**Review by abaiken — COMMENTED** [review]
This makes sense to me. I think that the `null` type is not supported in openapi 3.0.0 - when I load this file into swagger, I get errors, we might have to do `nullable=True` instead

**Review by romanblanco — APPROVED** [review]
Tested by regenerating a new client in https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/15

**Comment by lpichler** [comment]
> @lpichler can you please also change your documentation? Thank you!

I will cover this in follow-up PR.

**Pull request merged**
