### PR TITLE
Adding the migration file to support the "admin_default" flag 

### PR DESCRIPTION
**Pull request by casey-williams-rh**
Adding the migration file to support the addition of the column "admin_default" to `management_role` and `management_group`

## Link(s) to Jira
- https://issues.redhat.com/browse/RHCLOUD-16781

## Description of Intent of Change(s)
We'll want to add the following flags to RBAC to identify admin default groups and roles, with default values of "false":

- management_role#admin_default
- management_group#admin_default

This migration needs to be applied before the model changes.

## Local Testing

- Local API Testing == `Passed` ✅
- TOX Tesitng == `Passed` ✅

## Checklist
- [ ] if API spec changes are required, is the spec updated?
- [ ] are there any pre/post merge actions required? if so, document here.
- [ ] are theses changes covered by unit tests?
- [ ] if warranted, are documentation changes accounted for?
- [X] does this require migration changes?
  - [ ] if yes, are they backwards compatible?
- [ ] is there known, direct impact to dependent teams/components?
  -  if yes, how will this be handled?

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Practices Checklist
- [X] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [X] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [X] Data Protection
- [ ] Communication Security
- [X] System Configuration
- [X] Database Security
- [ ] File Management
- [ ] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by coderbydesign** [comment]
@casey-williams-rh I made this a draft so we can hold until the schema migration is done, based on our conversation last week. 😄

**Comment by coderbydesign** [comment]
Chatted with Casey about the failures, and it due to the fact that the model changes are not in this PR. The migration adds a not-null constraint by default, but the default value they were generated with `default=False` is in the model code only, not the DB. This means any role or group created without `admin_default=` supplied will fail due to the constraint. 

Since we're waiting to merge this until the migration is complete, we may be able to just have the model and code change in the same PR. Otherwise we'll need to:

- regenerate the migration with `null=True` in the model
- run the migration up
- add the model change and release
- enforce the constraint and add a data migration to backfill

**Review by astrozzc — APPROVED** [review]
LGTM

**Review by mjholder — APPROVED** [review]
LGTM

**Comment by coderbydesign** [comment]
@casey-williams-rh I've opened #661 which should unblock this.

**Pull request merged**
