### PR TITLE
Require "parent_id" field on Workspace POST

### PR DESCRIPTION
**Pull request by coderbydesign**
## Link(s) to Jira
- https://issues.redhat.com/browse/RHCLOUD-35802

## Description of Intent of Change(s)
We should be requiring `parent_id` on `POST` requests for `Workspace` objects

## Local Testing
Verify unit tests or send a `POST` request with/without `parent_id`.

## Checklist
- [ ] if API spec changes are required, is the spec updated?
- [ ] are there any pre/post merge actions required? if so, document here.
- [x] are theses changes covered by unit tests?
- [ ] if warranted, are documentation changes accounted for?
- [ ] does this require migration changes?
  - [ ] if yes, are they backwards compatible?
- [ ] is there known, direct impact to dependent teams/components?
  - [ ] if yes, how will this be handled?

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Practices Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by lpichler** [comment]
@coderbydesign Is needed to change anything related in openapi/tsp spec file ?

**Review by lpichler — APPROVED** [review]

**Comment by coderbydesign** [comment]
@lpichler good call, I'll take a look/update that.

**Review by astrozzc — APPROVED** [review]
LGTM!

**Pull request merged**
